"""
Django migration 0001_initial.

Auto-generated by Django 4.1.7 on 2026-03-30 11:49.
"""

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    """Initial migration for CustomUser, WordsData, WordTranslation."""

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(blank=True, null=True, verbose_name='last login')
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Designates that this user has all permissions without '
                            'explicitly assigning them.'
                        ),
                        verbose_name='superuser status'
                    )
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={'unique': 'A user with that username already exists.'},
                        help_text=(
                            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'
                        ),
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name='username'
                    )
                ),
                (
                    'first_name',
                    models.CharField(blank=True, max_length=150, verbose_name='first name')
                ),
                (
                    'last_name',
                    models.CharField(blank=True, max_length=150, verbose_name='last name')
                ),
                (
                    'email',
                    models.EmailField(blank=True, max_length=254, verbose_name='email address')
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status'
                    )
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'Designates whether this user should be treated as active. '
                            'Unselect this instead of deleting accounts.'
                        ),
                        verbose_name='active'
                    )
                ),
                (
                    'date_joined',
                    models.DateTimeField(default=django.utils.timezone.now,
                                         verbose_name='date joined')
                ),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_rate', models.IntegerField(default=0, verbose_name='Рейтинг ответов')),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            'The groups this user belongs to. A user will get all permissions '
                            'granted to each of their groups.'
                        ),
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups'
                    )
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions'
                    )
                ),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users_data',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WordsData',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'original',
                    models.CharField(max_length=255, unique=True, verbose_name='Слово на сербском')
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='words_images/',
                        verbose_name='Изображение слова'
                    )
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь'
                    )
                ),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'db_table': 'words_data',
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('translated', models.CharField(max_length=255, verbose_name='Перевод')),
                (
                    'word',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.wordsdata',
                        verbose_name='Слово'
                    )
                ),
            ],
            options={
                'verbose_name': 'Перевод слова',
                'verbose_name_plural': 'Переводы слов',
                'db_table': 'word_translation',
            },
        ),
    ]
